services:
  kafka:
    image: apache/kafka:latest
    container_name: chat-app-kafka
    volumes:
      - kafka-data:/var/lib/kafka/data
    ports:
      - "9092:9092"
    networks:
      - chat-app-network
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: CONTROLLER://0.0.0.0:9093,PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      KAFKA_LOG_DIRS: /var/lib/kafka/data

      KAFKA_CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
  redis:
      image: redis/redis-stack:7.4.0-v8
      container_name: chat-app-redis
      restart: unless-stopped
      volumes:
        - redis_data:/data
      networks:
        - chat-app-network
      ports:
        - "6379:6379"
        - "8001:8001"
  auth-postgres:
      image: postgres:17
      container_name: auth-postgres
      restart: unless-stopped
      environment:
        - POSTGRES_USER=chat_app_admin
        - POSTGRES_PASSWORD=chat_app_admin
        - POSTGRES_DB=chat_app_db
      volumes:
        - auth_pgdata:/var/lib/postgresql/data
      networks:
        - chat-app-network
      ports:
        - "5432:5432"

volumes:
  kafka-data:
  redis_data:
  auth_pgdata:

networks:
  chat-app-network:
    name: chat-app-network
